version: '3'
services:
  localstack:
    container_name: ${LOCALSTACK_DOCKER_NAME-localstack_main}
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=local
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=true
    volumes:
      - "./tmp/localstack:/tmp/localstack"
      - "./tmp/localstack/run/docker.sock:/var/run/docker.sock"